//go:build some_tag

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type Account struct {
	ID        int64     `db:"id" json:"id"`
	Owner     string    `db:"owner" json:"owner"`
	Balance   int64     `db:"balance" json:"balance"`
	Currency  string    `db:"currency" json:"currency"`
	CreatedAt time.Time `db:"created_at" json:"createdAt"`
}

type Entry struct {
	ID        int64 `db:"id" json:"id"`
	AccountID int64 `db:"account_id" json:"accountId"`
	// can e negative or positive
	Amount    int64     `db:"amount" json:"amount"`
	CreatedAt time.Time `db:"created_at" json:"createdAt"`
}

type Transfer struct {
	ID            int64 `db:"id" json:"id"`
	FromAccountID int64 `db:"from_account_id" json:"fromAccountId"`
	ToAccountID   int64 `db:"to_account_id" json:"toAccountId"`
	// must be positive
	Amount    int64     `db:"amount" json:"amount"`
	CreatedAt time.Time `db:"created_at" json:"createdAt"`
}
